---

- name: Install apache
  yum:
    name: httpd
    state: present

- name: Start apache
  service:
    name: httpd
    state: started

- name: Create custom index.html
  shell: echo "Welcome to Ansible" > /var/www/html/index.html

...

